### ISSUE TITLE
Runtime Status: Processing Failed

### ISSUE THREAD

**Issue by Satur-Vadim** [jauntybrain/flow-links-extension#15]
<img width="940" alt="image" src="https://github.com/user-attachments/assets/83a55fab-d1d3-44c7-842d-a2e502fb8dcc">

After installing the extension Using the Firebase console https://console.firebase.google.com/project/_/extensions/install?ref=jauntybrain/firebase-flow-links@0.1.5
Error log: 
```
Initialization error: Error: 5 NOT_FOUND: 
    at callErrorFromStatus (/workspace/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /workspace/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/workspace/node_modules/@grpc/grpc-js/build/src/client.js:160:32)
    at ServiceClientImpl.<anonymous> (/workspace/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at /workspace/node_modules/@google-cloud/firestore/build/src/v1/firestore_client.js:227:29
    at /workspace/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16
    at repeat (/workspace/node_modules/google-gax/build/src/normalCalls/retries.js:80:25)
    at /workspace/node_modules/google-gax/build/src/normalCalls/retries.js:118:13
    at OngoingCallPromise.call (/workspace/node_modules/google-gax/build/src/call.js:67:27)
    at NormalApiCaller.call (/workspace/node_modules/google-gax/build/src/normalCalls/normalApiCaller.js:34:19)
    at /workspace/node_modules/google-gax/build/src/createApiCall.js:84:30
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Caused by: Error
    at WriteBatch.commit (/workspace/node_modules/@google-cloud/firestore/build/src/write-batch.js:433:23)
    at DocumentReference.create (/workspace/node_modules/@google-cloud/firestore/build/src/reference.js:323:14)
    at CollectionReference.add (/workspace/node_modules/@google-cloud/firestore/build/src/reference.js:2322:28)
    at /workspace/lib/index.js:52:26
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /workspace/node_modules/firebase-functions/lib/common/providers/tasks.js:53:17 {
  code: 5,
  details: '',
  metadata: Metadata {
    internalRepr: Map(1) { 'x-debug-tracking-id' => [Array] },
    options: {}
  },
  note: 'Exception occurred in retry method that was not classified as transient'
}
```

This error is likely due to a failed attempt to create a document in Firestore.
Could you please advise how this can be fixed?

**Comment by johnsibly** [comment]
Hi @Satur-Vadim I found the same issue.
I think the problem is that the extension assumes you already have a Firestore Database set up in your project.

It tries to create a collection within this database but that fails.

I found that creating a new Firestore Database before installing the extension allows to to install.
Do to this I just left the database id blank which is the default.

<img width="855" alt="Image" src="https://github.com/user-attachments/assets/aa2f9f03-466b-4747-a4cd-cebcff5d2165" />

**Comment by badaz** [comment]
I had the error too during initialization and found out after some hours of searching that it was caused by the fact that I had chosen a name different than "(default)" for my Firestore database.  After deleting my DB and recreating it with name "(default)", initialization proceeded without error. If having a database named "(default)" is indeed a requirement for this extension to initialize properly, then I believe it should be specified somewhere in the setup guide.
